support local connections without ssh
mojin-robotics/robmuxinator pull request #11
Opened 2024-07-15 12:45 UTC by fmessmer

needed for https://github.com/4am-robotics/amr_deployment/pull/48

2024-07-15 12:47 UTC, fmessmer commented
Why can we not just mount the local ssh settings into the Dev Container?

2024-07-16 13:45 UTC, benmaidel requested changes

2024-07-16 13:45 UTC, benmaidel commented on robmuxinator/robmuxinator.py
> +        self._use_local_connection = self._hostname == "localhost" \
localhost could also be 127.0.0.1

2024-07-17 09:27 UTC, fmessmer commented
I considered @benmaidel's comment plus some additional pylint fixes and also bumped the robmuxinator version

@cmaneth can you make me collaborator, so I can push my changes to your branch?
then, I can merge this contribution...

2024-07-17 09:42 UTC, merged