fix stderr stdout output handling for remote connections
mojin-robotics/robmuxinator pull request #20
Opened 2024-10-14 11:51 UTC by pgehring

ref https://github.com/4am-robotics/orga/issues/6934

This PR fixes the exception during SSH comand sending.

2024-10-14 11:58 UTC, pgehring commented
runs on `mrl-7`

2024-10-14 12:01 UTC, Deleh requested changes

2024-10-14 12:01 UTC, Deleh commented on robmuxinator/robmuxinator.py
> -                    returncode = process.returncode
Just a formal guess without testing this.. I think the `wait_for_exit` feature for `localhost` connections isn't present anymore.

2024-10-16 15:19 UTC, Deleh approved these changes
Works for me as expected :+1:

@cmaneth feel free to merge this if it fixes your issue.

2024-10-25 07:10 UTC, merged